site_name: SuHan Yoon's Technical Report
site_url: https://ysh-research.github.io/YSH-research.io/
# 🔴 붉은 계열: red, pink, purple, deep purple
# 🔵 푸른 계열: indigo (기본값), blue, light blue, cyan, teal
# 🟢 초록 계열: green, light green, lime
# 🟡 노란/오렌지 계열: yellow, amber, orange, deep orange
# 🟤 무채색/기타: brown, grey, blue grey, black, white
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: default
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Research:
      - research.md
      - VMax _ IL,RL: Research/BC-SAC_VMax.md
      - DiffusionDriveV2 _ E2E,RL: Research/DiffusionDriveV2_E2E,RL.md
      - DiffusionPlanner _ BC: Research/DiffusionPlanner_Nuplan.md
  - Projects:
      - Project/projects.md
      - Computer Resource Management & Statistics:
          - Project/Computer-Resource-Management/computer-resource-management.md
      - ROS2 CycloneDDS Setting: Project/Computer-Resource-Management/ROS2-cyclonedds-setting.md
      - CARET _ ROS2 Runtime Analysis: Project/Computer-Resource-Management/CARET-ROS2-runtime-analysis.md
  - Study: study.md
  - Lectures: lecture.md
  - Presentations:
      - Overview: Presentations/presentations.md
      - Academic Seminars: Presentations/academic-seminars.md
      - Lab Seminars: Presentations/lab-seminars.md
  - CV: cv.md
  - Publications: publications.md
  - Competition: competition.md

