site_name: SuHan Yoon's Technical Report
site_url: https://ysh-research.github.io/
# 🔴 붉은 계열: red, pink, purple, deep purple
# 🔵 푸른 계열: indigo (기본값), blue, light blue, cyan, teal
# 🟢 초록 계열: green, light green, lime
# 🟡 노란/오렌지 계열: yellow, amber, orange, deep orange
# 🟤 무채색/기타: brown, grey, blue grey, black, white
theme:
  name: material
  logo: Assets/Logo.png
  palette:
    scheme: default
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - glightbox

extra_css:
  - Stylesheets/Extra.css

extra_javascript:
  - Javascripts/Mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Research: Research/Research.md
  - Projects: Project/Projects.md
  - Study: Study/Study.md
  - Lectures: Lecture/Lecture.md
  - Teaching: Teaching/Teaching.md
  - Presentations: Presentations/Presentations.md
  - CV: CV/CV.md
  - Publications: Publications/Publications.md
  - Competition: Competition/Competition.md

  